export const shoes = [
  {
    id: 1,
    title: "Sac Mentos",
    colors: "White Laser-Purple",
    rarity: "1 / 400",
    brand: "Nike",
    sillo: "Jordan Retro 3",
    date: "2025-01-01",
    price: 1100,
    source: "/release/sacremento3home.png",
  },
  {
    id: 2,
    title: "Bobcats",
    colors: "White Orange Navy",
    rarity: "1 / 6000",
    brand: "Nike",
    sillo: "Jordan Retro 3",
    date: "2025-01-01",
    price: 450,
    source: "/release/bobcat3home.png",
  },
  {
    id: 3,
    title: "Aire",
    colors: "Orange + Mercury + Black",
    rarity: "1 / 1000",
    brand: "Echo",
    sillo: "Firefly 6",
    date: "2025-01-08",
    price: 2000,
    source: "/release/airecho6.png",
  },
  {
    id: 4,
    title: "Bobcat Tens",
    colors: "White Orange Navy",
    rarity: "1 / 1000",
    brand: "Nike",
    sillo: "Jordan Retro 11",
    date: "2025-01-16",
    price: 450,
    source: "/release/bobcat10.png",
  },
  {
    id: 5,
    title: "Cream",
    colors: "White",
    rarity: "1 / 2000",
    brand: "Nike",
    sillo: "Jordan Retro 7",
    date: "2025-01-22",
    price: 1500,
    source: "/release/cream7s.png",
  },
  {
    id: 6,
    title: "Georgetown",
    colors: "White",
    rarity: "1 / 3000",
    brand: "Nike",
    sillo: "Jordan Retro 8",
    date: "2025-01-29",
    price: 2500,
    source: "/release/georgetown8s.png",
  },
  {
    id: 7,
    title: "Genie",
    colors: "White + Gold + Black",
    rarity: "1 / 1000",
    brand: "Echo",
    sillo: "Firefly 1",
    date: "2025-02-05",
    price: 600,
    source: "/release/fireflyecho1.png",
  },
  {
    id: 8,
    title: "Deep Black",
    colors: "White Black",
    rarity: "1 / 3600",
    brand: "Nike",
    sillo: "Jordan Retro 4",
    date: "2025-02-13",
    price: 1100,
    source: "/release/deepblack4s.png",
  },
  {
    id: 9,
    title: "Petals",
    colors: "White + Lavender",
    rarity: "1 / 30000",
    brand: "Nike",
    sillo: "Air Force 1",
    date: "2025-02-20",
    price: 375,
    source: "/release/lavenderair1s.png",
  },
  {
    id: 10,
    title: "White Ferrari",
    colors: "White + Red + Black",
    rarity: "1 / 1000",
    brand: "Nike",
    sillo: "Jordan Retro 11",
    date: "2025-02-27",
    price: 6500,
    source: "/release/ferrari14s.png",
  },
];
